version: "3.3"

services:
  # Base de datos
  mysql_umg_container_db:
    image: mysql:8.1.0
    restart: always
    container_name: mysql_umg_container_db
    env_file:
      - compose-variables.env
    ports:
      - 3357:3306
    expose:
      - 3357
    volumes:
      - umg_volume_data:/var/lib/mysql
#      - ./db:/docker-entrypoint-initdb.d


  phpmyadmin_container:
    image: phpmyadmin/phpmyadmin
    restart: always
    container_name: phpmyadmin_container
    links:
      - mysql_umg_container_db
    env_file:
      - compose-variables.env
    ports:
      - 8081:80

volumes:
  umg_volume_data: