CREATE TABLE db_drivexport.producto (codigoproducto VARCHAR(30) NOT NULL , nombreproducto VARCHAR(100) NOT NULL , descripcionproducto VARCHAR(300) NOT NULL , cantidadproducto INT NOT NULL , preciounitario FLOAT NOT NULL , fecha TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , PRIMARY KEY (codigoproducto(30))) ENGINE = InnoDB COMMENT = 'Creacion de la tabla producto';

-- Insertar datos
INSERT INTO `producto` (`codigoproducto`, `nombreproducto`, `descripcionproducto`, `cantidadproducto`, `preciounitario`, `fecha`) VALUES ('aa123', 'Carro Tesla', 'Increible carro testa que te lleva a la luna', '0', '250000', CURRENT_TIMESTAMP), ('aa124', 'Motoneta electrica', 'Libertad en dos ruedas', '0', '12500', CURRENT_TIMESTAMP), ('aa125', 'Motoneta electrica 2', 'Libertad en dos ruedas', '0', '13500', CURRENT_TIMESTAMP), ('aa125', 'Bicicleta sport', 'Diversion todo terreno', '0', '18500', CURRENT_TIMESTAMP), ('aa126', 'Patineta', 'Vuelta a la juventud', '0', '3500', CURRENT_TIMESTAMP);

INSERT INTO `producto` (`codigoproducto`, `nombreproducto`, `descripcionproducto`, `cantidadproducto`, `preciounitario`, `fecha`) VALUES ('bb123', 'Moto electrica', 'Increible moto electrica', '0', '23000', CURRENT_TIMESTAMP), ('bb124', 'Moto v2', 'Libertad en dos ruedas', '0', '14500', CURRENT_TIMESTAMP), ('bb125', 'Motocicleta v3', 'Libertad en dos ruedas', '0', '20000', CURRENT_TIMESTAMP), ('bb126', 'Motocicleta sport', 'Diversion todo terreno', '0', '18500', CURRENT_TIMESTAMP), ('bb129', 'Pulsar', 'Vuelta a la juventud', '0', '22500', CURRENT_TIMESTAMP);

INSERT INTO `producto` (`codigoproducto`, `nombreproducto`, `descripcionproducto`, `cantidadproducto`, `preciounitario`, `fecha`) VALUES ('cc123', 'Ferrari Tesla', 'El mas veloz de mundo', '0', '290000', CURRENT_TIMESTAMP), ('cc124', 'Hilux', 'Todo terreno', '0', '123500', CURRENT_TIMESTAMP), ('cc125', 'Carro 2', 'Libertad por donde andes', '0', '563500', CURRENT_TIMESTAMP), ('cc121', 'Bicicleta sport x', 'Diversion manejado', '0', '318500', CURRENT_TIMESTAMP), ('ll126', 'Patineta 3', 'Vuelta a la juventud', '0', '355600', CURRENT_TIMESTAMP);

INSERT INTO `producto` (`codigoproducto`, `nombreproducto`, `descripcionproducto`, `cantidadproducto`, `preciounitario`, `fecha`) VALUES ('ww123', 'Porsche Tesla', 'La velocidad en tus manos', '0', '550000', CURRENT_TIMESTAMP), ('ww124', 'Doble cabina', 'Listo para el camino', '0', '33500', CURRENT_TIMESTAMP), ('ww125', 'Hilux 2', 'El camino sin limites', '0', '139500', CURRENT_TIMESTAMP), ('ww129', 'Bicicleta sport 2e', 'Diversion para todos', '0', '185940', CURRENT_TIMESTAMP), ('pp126', 'Patineta 25', 'Vuelta a la juventud', '0', '263500', CURRENT_TIMESTAMP);

INSERT INTO `producto` (`codigoproducto`, `nombreproducto`, `descripcionproducto`, `cantidadproducto`, `preciounitario`, `fecha`) VALUES ('yy123', 'Lamborgini Tesla', 'Rapido como la luz', '0', '950000', CURRENT_TIMESTAMP), ('yy124', 'Camion de carga', 'Para todo trabajo', '0', '128900', CURRENT_TIMESTAMP), ('yy125', 'Hilux electrica 2', 'Veloz como el rayo macqueen', '0', '285500', CURRENT_TIMESTAMP), ('ww146', 'Bicicleta 3xl', 'Diversion todo terreno 1', '0', '185420', CURRENT_TIMESTAMP), ('ii126', 'Patineta 89', 'Vuelta a la juventud 5', '0', '32500', CURRENT_TIMESTAMP);

